### PR TITLE
Adding new gems, generating sdk with latest AutoRest

### PR DESCRIPTION
**Pull request by veronicagg**
Updated Rakefile, added new gems from available azure-rest-api-specs and regenerated gems with latest autorest.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@veronicagg__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by vishrutshah** [comment]
@veronicagg I believe that your regen removed the files from `azure_mgmt_cognitive_services, azure_mgmt_machine_learning, azure_mgmt_mobile_engament, azure_mgmt_powerbi_embedded, azure_mgmt_server_management, azure_mgmt_service_bus` and `azure_mgmt_traffic_manager`. 

The reason is that we also need update Rake file with the same folder name (with _ in the name) as the hash key.

**Comment by veronicagg** [comment]
@vishrutshah thanks for catching it, I've updated the PR.

**Comment by vishrutshah** [comment]
@veronicagg Changes LGTM. 

In case you get a chance to add https://github.com/Azure/azure-rest-api-specs/blob/master/arm-mediaservices/2015-10-01/swagger/media.json as well, that'd be great. it was added a week ago in the repo.

**Comment by veronicagg** [comment]
@vishrutshah thanks! I've updated the PR.

**Comment by vishrutshah** [comment]
@veronicagg LGTM

**Comment by veronicagg** [comment]
@vishrutshah Thanks!

**Pull request merged**
