### PR TITLE
Remove resource_management folder

### PR DESCRIPTION
**Pull request by vishrutshah**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vishrutshah__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by vishrutshah** [comment]
@veronicagg for some time. we were thinking of moving all the gems outside the 'resource_management' folder. Here is the PR that eliminates the 'resource_management' folder use. Please have a look at it when you get a chance.

**Comment by devigned** [comment]
What do you think about moving the gemspecs out to the root?

**Comment by vishrutshah** [comment]
@devigned Is there any reason why we want to move all the gemspecs outside. We have one top-level gemspec outside named as '`azure_arm.gemspec`'.

**Comment by devigned** [comment]
That works.

**Comment by veronicagg** [comment]
@vishrutshah Changes looks good, please double check the readme, some updates on links in 'Getting started Samples' and instructions in 'Development Environment Setup' need updates based on this change. Thanks!

**Comment by vishrutshah** [comment]
@veronicagg thanks for catching that. I've updated readme accordingly.

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
